export type CommandDef = {
  id: string;
  label: string;
  description: string;
  defaultKey: string | null;
  category: "Navigation" | "File" | "Tabs" | "View" | "Sync" | "Editing";
};

export const COMMAND_REGISTRY: CommandDef[] = [
  {
    id: "pane.next",
    label: "Next pane",
    description: "Cycle focus to the next pane",
    defaultKey: "F6",
    category: "Navigation",
  },
  {
    id: "pane.prev",
    label: "Previous pane",
    description: "Cycle focus to the previous pane",
    defaultKey: "Shift+F6",
    category: "Navigation",
  },
  {
    id: "view.hint",
    label: "Hint mode (click anything)",
    description: "Overlay letter labels for keyboard click",
    defaultKey: "F",
    category: "Navigation",
  },
  {
    id: "view.search",
    label: "Focus search",
    description: "Jump to the search bar",
    defaultKey: "Ctrl+F",
    category: "Navigation",
  },
  {
    id: "view.focusTree",
    label: "Focus file tree",
    description: "Reveal sidebar and focus tree",
    defaultKey: "Ctrl+Shift+E",
    category: "Navigation",
  },
  {
    id: "view.toggleSidebar",
    label: "Toggle sidebar",
    description: "Show or hide the sidebar",
    defaultKey: "Ctrl+B",
    category: "View",
  },
  {
    id: "view.help",
    label: "Show keyboard shortcuts",
    description: "Open the shortcuts cheat sheet",
    defaultKey: "Ctrl+/",
    category: "View",
  },
  {
    id: "view.settings",
    label: "Open settings",
    description: "Open the settings modal",
    defaultKey: "Ctrl+,",
    category: "View",
  },
  {
    id: "view.commandPalette",
    label: "Command palette",
    description: "(stub)",
    defaultKey: "Ctrl+Shift+P",
    category: "View",
  },
  {
    id: "file.new",
    label: "New file under root",
    description: "Create untitled-N.md in vault root and open it",
    defaultKey: "Ctrl+N",
    category: "File",
  },
  {
    id: "file.newScratch",
    label: "New scratch buffer",
    description: "Open an in-memory tab not backed by a file",
    defaultKey: "Ctrl+Shift+N",
    category: "File",
  },
  {
    id: "file.save",
    label: "Save active tab",
    description: "Write the active tab to disk",
    defaultKey: "Ctrl+S",
    category: "File",
  },
  {
    id: "file.fuzzyOpen",
    label: "Fuzzy open / search",
    description: "Focus the search bar to find a file",
    defaultKey: "Ctrl+P",
    category: "File",
  },
  {
    id: "file.move",
    label: "Move file",
    description: "Move the active file to a different path",
    defaultKey: "Ctrl+M",
    category: "File",
  },
  {
    id: "file.rename",
    label: "Rename file",
    description: "Rename the active file's basename",
    defaultKey: "F2",
    category: "File",
  },
  {
    id: "view.refresh",
    label: "Refresh tree",
    description: "Reload file tree from disk (catches external changes)",
    defaultKey: "F5",
    category: "View",
  },
  {
    id: "tab.reopen",
    label: "Reopen closed tab",
    description: "Reopen the most recently closed file tab",
    defaultKey: "Ctrl+Shift+T",
    category: "Tabs",
  },
  {
    id: "tab.next",
    label: "Next tab",
    description: "Switch to the next tab",
    defaultKey: "Ctrl+Tab",
    category: "Tabs",
  },
  {
    id: "tab.prev",
    label: "Previous tab",
    description: "Switch to the previous tab",
    defaultKey: "Ctrl+Shift+Tab",
    category: "Tabs",
  },
  {
    id: "tab.goto.1",
    label: "Go to tab 1",
    description: "Activate tab 1",
    defaultKey: "Ctrl+1",
    category: "Tabs",
  },
  {
    id: "tab.goto.2",
    label: "Go to tab 2",
    description: "Activate tab 2",
    defaultKey: "Ctrl+2",
    category: "Tabs",
  },
  {
    id: "tab.goto.3",
    label: "Go to tab 3",
    description: "Activate tab 3",
    defaultKey: "Ctrl+3",
    category: "Tabs",
  },
  {
    id: "tab.goto.4",
    label: "Go to tab 4",
    description: "Activate tab 4",
    defaultKey: "Ctrl+4",
    category: "Tabs",
  },
  {
    id: "tab.goto.5",
    label: "Go to tab 5",
    description: "Activate tab 5",
    defaultKey: "Ctrl+5",
    category: "Tabs",
  },
  {
    id: "tab.goto.6",
    label: "Go to tab 6",
    description: "Activate tab 6",
    defaultKey: "Ctrl+6",
    category: "Tabs",
  },
  {
    id: "tab.goto.7",
    label: "Go to tab 7",
    description: "Activate tab 7",
    defaultKey: "Ctrl+7",
    category: "Tabs",
  },
  {
    id: "tab.goto.8",
    label: "Go to tab 8",
    description: "Activate tab 8",
    defaultKey: "Ctrl+8",
    category: "Tabs",
  },
  {
    id: "tab.goto.last",
    label: "Go to last tab",
    description: "Activate the last tab (Chrome-style)",
    defaultKey: "Ctrl+9",
    category: "Tabs",
  },
  {
    id: "tab.close",
    label: "Close tab",
    description: "Close the active tab",
    defaultKey: "Ctrl+W",
    category: "Tabs",
  },
  {
    id: "tab.closeAll",
    label: "Close all tabs",
    description: "Close every open tab",
    defaultKey: "Ctrl+Shift+W",
    category: "Tabs",
  },
  {
    id: "app.quit",
    label: "Quit Clawless",
    description: "Exit the app entirely (also closes tray)",
    defaultKey: "Ctrl+Q",
    category: "View",
  },
];
